version: 2

models:
- name: styrk_akademiske_yrker
  description: "styrk model"
  columns:
    - name: code
      description: "Styrk kode"
      tests:
        - not_null
    - name: parentCode
      description: "kode til parent"
    - name: level
      description: "nivå"
      tests:
        - not_null
    - name: name
      description: "Styrk navn"
      tests:
        - unique
        - not_null
    - name: shortName
      description: "kort navn"
    - name: notes
      description: "notater"

- name: styrk_yrker_med_notater
  description: "styrk model"
  columns:
    - name: code
      description: "Styrk kode"
      tests:
        - not_null
    - name: parentCode
      description: "kode til parent"
    - name: level
      description: "nivå"
      tests:
        - not_null
    - name: name
      description: "Styrk navn"
      tests:
        - unique
        - not_null
    - name: shortName
      description: "kort navn"
    - name: notes
      description: "notater"
