
version: 2

models:
    - name: styrk_modell
      description: "A starter dbt model"
      columns:
          - name: code
            description: "Styrk kode"
          - name: parentCode
            description: "kode til parent"
          - name: level
            description: "nivå"
          - name: name
            description: "Styrk navn"
          - name: shortName
            description: "kort navn"
          - name: notes
            description: "notater"
