styrk:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dataplattform-dev-9da3
      schema: dbt_demo
      threads: 4
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
