project:
  type: book

book:
  title: "quartobook"
  author: "Jane Doe"
  date: "1/11/2024"
  chapters:
    - index.qmd
    - blah.ipynb
    - intro.qmd

format:
  html:
    theme: sandstone
    number-sections: false


