name: "Knada GKE: Build nks-statistikk jupyterhub image"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - Dockerfile

env:
  IMAGE: ghcr.io/navikt/test-knada

jobs:
  build:
    name: Build jupyterlab image for nks-statistikk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "TAG=$(git log -1 --pretty=%ad --date=format:%Y-%m-%d)-$(git log --pretty=format:'%h' -n 1)" >> $GITHUB_ENV
      - run: docker build -t $IMAGE:$TAG .
      - run: docker push $IMAGE:$TAG
